### ISSUE TITLE
Check that all permissions match the permissions used on the InfectedCrew page.

### ISSUE THREAD

**Issue by halvors** [InfectedLan/InfectedCompo#8]

**Comment by petterroea** [comment]
What do you mean?

**Comment by halvors** [comment]
I mean that we actually use the same permission string for each feature that is implemented on both sites.

**Comment by halvors** [comment]
Otherwise the permissions will not work. Just make sure it matches the permissions database table.

**Comment by petterroea** [comment]
Aight.

**Comment by petterroea** [comment]
This should be correct now
